apiVersion: v1
kind: Service
metadata:
  #The name of the Kubernetes Service to be created 
  #in the Kubernetes cluster
  name: oneapp 
spec:
  selector:
    app: one-app 
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 801 #Service port
    targetPort: 801 #The port for the React.js application container
